export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const LOAD_USER_INFO_FAIL = "LOAD_USER_INFO_FAIL";
export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const CLEAR_USER_MESSAGES = "CLEAR_USER_MESSAGES";

